# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gophersay < Formula
  desc ""
  homepage "https://github.com/scraly/homebrew-tools"
  version "1.0.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scraly/gophersay/releases/download/v1.0.1/gophersay_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "3ac4da7f8882ad3ec82e9d7a5e3342d2463437275e0c72086af624e76dcb784c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/scraly/gophersay/releases/download/v1.0.1/gophersay_1.0.1_Darwin_arm64.tar.gz"
      sha256 "f311f5daf5a8556b1197e10483ab4c17c22ef47a790554ead7ea9478a0466c4b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/scraly/gophersay/releases/download/v1.0.1/gophersay_1.0.1_Linux_x86_64.tar.gz"
      sha256 "3e9bb2b51501df72cb007c4978bdc9997a6ff83479b1f189fd8f4b73b55b5037"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scraly/gophersay/releases/download/v1.0.1/gophersay_1.0.1_Linux_arm64.tar.gz"
      sha256 "5ba1bee7e9a23fcb732176580f251b887a372a32211e408d7f04638a95b65ded"
    end
  end

  def install
    bin.install "gophersay"
  end
end
