# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tools < Formula
  desc ""
  homepage "https://github.com/scraly/homebrew-tools"
  version "1.0.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scraly/gophersay/releases/download/v1.0.1/gophersay_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "6453770e0c226134acd49635b29633675ad24c718986de06f3c9d5fb3e3339a3"
    end
    if Hardware::CPU.arm?
      url "https://github.com/scraly/gophersay/releases/download/v1.0.1/gophersay_1.0.1_Darwin_arm64.tar.gz"
      sha256 "e765853a5a971a6cf3144a191dc8b518733392d4604de1159f17d6e811c17bc7"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/scraly/gophersay/releases/download/v1.0.1/gophersay_1.0.1_Linux_x86_64.tar.gz"
      sha256 "fbe6cf70475b6b922d94248f932c08b3d3bbcc935ed8995dd8d7872283adcb9d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scraly/gophersay/releases/download/v1.0.1/gophersay_1.0.1_Linux_arm64.tar.gz"
      sha256 "7cf468f8bba38088bd4a03d3435af43a74d08264066b13a33cbc441310f556f2"
    end
  end

  def install
    bin.install "gophersay"
  end
end
